# Generated by Django 3.1.7 on 2021-03-07 17:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[''], size=None),
            preserve_default=False,
        ),
    ]
