# Generated by Django 3.1.7 on 2021-03-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_shopid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shopID',
        ),
        migrations.AddField(
            model_name='shop',
            name='productIDs',
            field=models.ManyToManyField(related_name='product_id', to='api.Product'),
        ),
    ]
