# Generated by Django 3.1.7 on 2021-03-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210308_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='anotherTest',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
